# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Learn_IOSUI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Learn_IOSUI

  target 'Learn_IOSUI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Learn_IOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Learn_IOSUI-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Learn_IOSUI-tvOS

  target 'Learn_IOSUI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
